config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :events
  resources :products

  get '/about',   to: 'about#about',   as: 'about'
  get '/contact', to: 'about#contact', as: 'contact'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :photo, :styles => { :large => "600x600>", :medium => "250x250>", :thumb => "100x100>" }
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	acts_as_sellable
	# attr_accessible :piggybak_sellable_attributes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	before_filter :get_upcoming_event, :get_latest_post, :get_new_product

	def about

	end

	def contact

	end

	private
		def get_latest_post
			@latest_post = Post.all.order(created_at: :desc).first
		end

		def get_upcoming_event
			@upcoming_event = Event.all.order(time: :asc).first
		end
		
		def get_new_product
			@new_product = Product.all.order(created_at: :desc).first
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper CalendarHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :get_event, :only => [:show, :edit, :update, :destroy]
	before_filter :get_latest_post, :get_new_product, :only => [:index, :show]

	def index
		@date = params[:month] ? Date.parse(params[:month] + "-01") : Date.today
		@events = Event.all.order(time: :asc).where("time >= ?",Date.today.to_datetime)
		get_event_days
	end

	def show
		
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)

		if @event.save
			flash[:success] = "New event created"
			redirect_to events_path
		else
			flash[:error] = "There was an error creating that event"
			render action: :new
		end
	end

	def edit
		
	end

	def update
		if @event.update_attributes(event_params)
			flash[:success] = "Event updated"
			redirect to event_path(@event)
		else
			flash[:error] = "There was an error updating that event"
			render action: :edit
		end
	end

	def destroy
		if @event.destroy
			flash[:success] = "Event deleted"
		else
			flash[:error] = "Event could not be deleted"
		end

		redirect_to events_path
	end

	private
		def event_params
			params.require(:event).permit(:name, :description, :time)
		end

		def get_event
			@event = Event.find(params[:id])
		end

		def get_event_days
			@event_days = {}

			Event.all.order(time: :asc).each do |event|
				@event_days[event.time.to_date] = event
			end
		end

		def get_latest_post
			@latest_post = Post.all.order(created_at: :desc).first
		end

		def get_new_product
			@new_product = Product.all.order(created_at: :desc).first
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :get_post, :only => [:show, :edit, :update, :destroy]
	before_filter :get_upcoming_event, :get_new_product, :only => [:index, :show]

	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def show
		
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			flash[:success] = "New post created"
			redirect_to posts_path
		else
			flash[:error] = "There was an error creating that post"
			render action: :new
		end
	end

	def edit
		
	end

	def update
		if @post.update_attributes(post_params)
			flash[:success] = "Post updated"
			redirect_to post_path(@post)
		else
			flash[:error] = "There was an error updating that post"
			render action: :edit
		end
	end

	def destroy
		if @post.destroy
			flash[:success] = "Post deleted"
		else
			flash[:error] = "Post could not be deleted"
		end

		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :raw_markdown)
		end

		def get_post
			@post = Post.find(params[:id])
		end

		def get_upcoming_event
			@upcoming_event = Event.all.order(time: :asc).first
		end

		def get_new_product
			@new_product = Product.all.order(created_at: :desc).first
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :get_product, :only => [:show, :edit, :update, :destroy]
	before_filter :get_upcoming_event, :get_latest_post, :only => [:index, :show]

	def index
		@products = Product.all
	end

	def show
		
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			flash[:success] = "New product created"
			redirect_to products_path
		else
			flash[:error] = "Product could not be saved"
			render action: :new
		end
	end

	def edit

	end

	def update
		if @product.update_attributes(product_params)
			flash[:success] = "Product updated"
			redirect_to products_path
		else
			flash[:error] = "Product could not be updated"
			render action: :edit
		end
	end

	def destroy
		if @product.destroy
			flash[:success] = "Product deleted"
		else
			flash[:error] = "Product could not be deleted"
		end

		redirect_to products_path
	end

	private
		def product_params
			params.require(:product).permit(:name, :description, :price, :photo)
		end

		def get_product
			@product = Product.find(params[:id])
		end

		def get_latest_post
			@latest_post = Post.all.order(created_at: :desc).first
		end

		def get_upcoming_event
			@upcoming_event = Event.all.order(time: :asc).first
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/about.html.erb
<div class="row">
	<div class="span9">
		<h1>About</h1>

		<p>Everything about everything</p>
	</div>
	<div class="span3">
		<%= render 'shared/sidebar' %>
	</div>
</div

app/views/about/contact.html.erb
<div class="row">
	<div class="span9">
		<h1>Contact Information</h1>

		<p>Contact number: </p>
		<p>Store Address: </p>
		<p>Hours? I guess? </p>
	</div>
	<div class="span3">
		<%= render 'shared/sidebar' %>
	</div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :time %><br>
		<%= f.datetime_field :time %>
	</div>
	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
	<div class="span9">
		<h1 class="page_title" style="text-align:center">Event Calendar</h1>
		<div id="calendar">
			<%= calendar(:year => @date.year, :month => @date.month, :first_day_of_week => 0) do |d| 
				if @event_days[d]
					["#{d.mday} \n #{link_to @event_days[d].name, event_path(@event_days[d])}", {:class => "specialDay"}]
				else
					[d.mday, {:class => "normalDay"}]
				end
			end %>
			<div id="month">
				<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
	    	<%=h @date.strftime("%B %Y") %>
	    	<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
	    </div>
  	</div>
		<%= link_to 'New Event', new_event_path %>
		<h2>Upcoming Events</h2>
		<% @events.each do |event| %>
			<div class="event" id="<%= dom_id(event) %>">
				<h3><%= link_to event.name, event_path(event) %></h3>
				<p class="event_time"><%= event.time %></p>
			</div>
		<% end %>
	</div>
	<div class="span3">
		<%= render 'shared/sidebar' %>
	</div>
</div>

app/views/events/new.html.erb
<h1>Create new event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<h4><%= @event.time %></h4>

<p><%= @event.description %></p><br>

<%= link_to 'Edit', edit_event_path %>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventsblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">

		<%= render 'shared/header' %>

		<div class="row">
			<div class="span12">
				<%= bootstrap_flash %>

				<% flash.each do |name, msg| %>
		  		<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>

				<%= yield %>
			</div>
		<div>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
  	<%= f.label :body %>
    <%= f.text_area :raw_markdown %>
    <div style="display:none;">
    	<input type="text" name="post[body]" id="post_body">
    </div>
   </div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<br><p>Live Preview</p><br>
	<div id="body-preview"></div>
<% end %>

<script type="text/javascript">
  setup_wmd({
    input: 	 "post_raw_markdown",
    preview: "body-preview",
    output:  "post_body"
  });
</script>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
	<div class="span12">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
	<div class="span9">
		<h1 class="page_title" style="text-align:center">Bloggin' It</h1>
		<%= link_to 'New Post', new_post_path %>
		<% @posts.each do |post| %>
			<div class="row">
				<div class="span9">
					<div class="post" id="<%= dom_id(post) %>">
						<h2 class="post_title"><%= post.title %></h2>
						<div class="post_body">
							<%= post.body.slice(0,500).html_safe + 
									(post.body.length > 500 ? '...' : '') %>
						</div>
						<%= link_to 'Read more', post_path(post) %><br>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="span3">
		<%= render "shared/sidebar", :locals => {:upcoming_event => @upcoming_event, :new_product => @new_product} %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1 class="post_title"><%= @post.title %></h1>

<div class="post_body">
	<%= @post.body.html_safe %>
</div>

<%= link_to 'Back', posts_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :price %>
		<%= f.number_field :price, step: 0.01 %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :photo %>
		<%= f.file_field :photo %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
	<div class="span9">
		<div class="row">
			<h1 class="page_title" style="text-align:center">Shop</h1>
			<% @products.each do |product| %>	
				<div class="span3">
					<%= image_tag product.photo.url(:medium) %><br>
					<h4><%= link_to product.name, product_path(product) %></h4>
					<p><%= product.price %></p>
					<%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: "Are you sure?" } %><br>
					<%= link_to 'Edit', edit_product_path(product) %><br>
				</div>
			<% end %>
		</div>
	</div>
	<div class="span3">
		<%= render 'shared/sidebar' %>
	</div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= image_tag @product.photo.url(:large) %>

<p><%= @product.price %></p><br>

<p><%= @product.description %></p><br>

<%= link_to 'Back', products_path %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
		<div class="row">
			<div class="span6 offset1">
				<h1>FLAMINGO VINTAGE</h1>
			</div>
		</div>
		<div class="row">
			<div class="span9 offset1">
				<h2><%= link_to 'Blog'  , posts_path %></h2>
				<h2><%= link_to 'Events' , events_path %></h2>
				<h2><%= link_to 'Shop'   , products_path %></h2>
				<h2><%= link_to 'About'  , about_path %></h2>
				<h2><%= link_to 'Contact', contact_path %></h2>
			</div>
		</div>
	</div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="well sidebar-nav">
	<% if @latest_post %>
		<div class="row">
			<div class="span3">
				<h3>Latest Blog</h3>
				<h4><%= link_to @latest_post.title, post_path(@latest_post) %></h4>
			</div>
		</div>
	<% end %>
	<% if @upcoming_event %>
		<div class="row">
			<div class="span3">
				<h3>Next Event</h3>
				<h4><%= link_to @upcoming_event.name, event_path(@upcoming_event) %></h4>
				<p><%= @upcoming_event.time %></p>
			</div>
		</div>
	<% end %>
	<% if @new_product %>
		<div class="row">
			<div class="span3">
				<h3>Newest Product</h3>
				<%= image_tag @new_product.photo.url(:thumb) %>
				<h4><%= link_to @new_product.name, product_path(@new_product) %></h4>
				<p><%= @new_product.price %></p>
			</div>
		</div>
	<% end %>
</div>